### ISSUE TITLE
Disabling Render Dragon is very misleading in the project's README.md.

### ISSUE THREAD

**Issue by Aetopia** [Swedeachu/SwimDragon#3]
The `README.md` file says:
```
Modifies the NVIDIA driver profile for Minecraft to have the hidden setting "Ray Tracing - (DXR)" to be set to false.
This forces bedrock to use the old rendering engine, fixing all the performance issues resulting in making the game smoother and have higher FPS.
This even fixes pink glitch somehow.
```

This is extremely misleading, since changing `Ray Tracing - (DXR)` makes Minecraft detect the system to have a non-RTX GPU and switches to `DX12` and not `DX12 RTX`. The game still uses RenderDragon regardless of what graphics API since the engine is hardcoded.

**Comment by Swedeachu** [comment]
did some rewording.
